# -*- mode: python ; coding: utf-8 -*-
import os
from pathlib import Path

# Project root directory
ROOT_DIR = Path(r'D:\\myapps\\rooa')

block_cipher = None

a = Analysis(
    ['startup.py'],
    pathex=[str(ROOT_DIR)],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('config', 'config'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_login',
        'flask_wtf',
        'flask_caching',
        'werkzeug',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'waitress',
        'models',
        'archive_models',
        'config_manager',
        'utils',
        'config',
        'app',
        'smart_knowledge',
        'forms',
        
        # Document processing - COMPLETE SET
        'docx',
        'docx.document',
        'docx.oxml',
        'docx.oxml.ns',
        'docx.text',
        'docx.text.paragraph',
        'docx.text.run',
        'docx.table',
        'PyPDF2',
        'PyPDF2._reader',
        'PyPDF2._writer',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.cell',
        'openpyxl.reader',
        'openpyxl.reader.excel',
        'openpyxl.writer',
        'openpyxl.writer.excel',
        'openpyxl.xml',
        'openpyxl.xml.functions',
        'openpyxl.xml.constants',
        'openpyxl.styles',
        'openpyxl.utils',
        'et_xmlfile',
        'pypdf',
        'fitz',
        'PyMuPDF',
        'img2pdf',
        
        # Image processing
        'PIL',
        'PIL._imaging',
        'PIL.Image',
        'PIL.ImageFile',
        'PIL.ImageOps',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageFilter',
        'PIL.ImageChops',
        'PIL._tkinter_finder',
        'cv2',
        'cv2.cv2',
        'cv2.data',
        'numpy.core._multiarray_umath',
        'pytesseract',
        
        # Chinese NLP
        'jieba',
        'jieba.analyse',
        'jieba._compat',
        'jieba.posseg',
        
        # Data - COMPLETE SET
        'numpy',
        'numpy.core',
        'numpy.core.multiarray',
        'numpy.core._multiarray_umath',
        'numpy.core.numerictypes',
        'numpy.core.defchararray',
        'numpy.lib',
        'numpy.lib.format',
        'numpy.fft',
        'numpy.linalg',
        'numpy.random',
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas.core',
        'pandas.core.frame',
        'pandas.core.series',
        'pandas.core.indexes',
        'pandas.io',
        'pandas.io.excel',
        'pandas.io.formats',
        
        # Network
        'requests',
        'requests.adapters',
        'requests.packages.urllib3',
        'requests.packages.urllib3.util',
        'bs4',
        'bs4.builder',
        'bs4.builder._lxml',
        'beautifulsoup4',
        'lxml',
        'lxml.etree',
        'lxml.html',
        
        # ML/NLP (optional)
        'sentence_transformers',
        'transformers',
        'transformers.modeling_utils',
        'transformers.tokenization_utils',
        'tokenizers',
        'huggingface_hub',
        'torch',
        'torch.nn',
        'torch.nn.functional',
        
        # Excel support - critical!
        'openpyxl.cell.cell',
        'openpyxl.styles.colors',
        'openpyxl.styles.fonts',
        'openpyxl.styles.fills',
        'openpyxl.styles.alignment',
        'openpyxl.styles.borders',
        'openpyxl.styles.protection',
        'openpyxl.styles.colors',
        'openpyxl.styles.numbers',
        'openpyxl.workbook.child',
        'openpyxl.worksheet.worksheet',
        'openpyxl.worksheet.dimensions',
        'openpyxl.worksheet.page',
        'openpyxl.utils.cell',
        'openpyxl.utils.exceptions',
        'openpyxl.xml.functions',
        
        # Misc
        'pickle',
        'json',
        're',
        'datetime',
        'collections',
        'time',
        'os',
        'sys',
        'pathlib',
        'threading',
        'logging',
        'tempfile',
        'shutil',
        'zipfile',
        'struct',
        'array',
        'math',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='智能服务办公平台',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,  # 可设置为 ico 文件路径
)
